version: '2'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile_db
    restart: always
    user: ${HOST_USER_ID}:${HOST_GROUP_ID}
    ports:
    - 127.0.0.1:3306:3306
    volumes:
    - ./mysql_data:/var/lib/mysql
    environment:
    - MYSQL_RANDOM_ROOT_PASSWORD=yes
    - MYSQL_DATABASE
    - MYSQL_USER
    - MYSQL_PASSWORD

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - MYSQL_HOST=db
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    depends_on:
    - db
    restart: always
#    darf nicht homeless sein!
#    user: ${HOST_USER_ID}:${HOST_GROUP_ID}
    volumes:
    - ./samples:/var/samples
    - ./genomes:/var/genomes
    environment:
    - MYSQL_HOST=db
    - MYSQL_DATABASE
    - MYSQL_USER
    - MYSQL_PASSWORD
    - WORKER_ID=worker1
      
  web:
    build:
      context: .
      dockerfile: Dockerfile_web
    depends_on:
    - db
    - worker
    restart: always
    ports:
    - 80:80
#    - 443:443
    volumes:
#    - ./www:/var/www
    - ./samples:/var/samples
    environment:
    - APACHE_RUN_USER=#${HOST_USER_ID}
    - APACHE_RUN_GROUP=#${HOST_GROUP_ID}
    - MYSQL_HOST=db
    - MYSQL_DATABASE
    - MYSQL_USER
    - MYSQL_PASSWORD
